# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c303a6f119f0382a28ef6bc6f0759b1aa2fba0553084459f3d014bb4e626b832a584b599f8477765bdc0d66425283033ac2e7cf28f1dd1138c36b34f7bcbb42

test:
  secret_key_base: 8c670b16da82b55fe045195b3f4cad8c7fce6e80ce7e0f3de31429f5bafcf5a4af520eecd1f50ec0639437851027bcb4f66ee61c1882556f35178092bad41aed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
